dist: xenial
sudo: false
latex: false
language: r
r: release
warnings_are_errors: false
cache:
    packages: true

before_install:    
 - sudo add-apt-repository universe
 - sudo apt update

apt_packages:
 #   - r-cran-tidyverse
 #   - r-cran-shiny
 #   - r-cran-shinydashboard
 #   - r-cran-viridis
 #   - r-cran-viridislite
 #   - r-cran-sf
 #   - r-cran-stars
 #   - r-cran-units
 #   - r-cran-classint
 #   - r-cran-htmltools
 #   - r-cran-htmlwidgets
 - libudunits2-0 #for r-cran-units when builing from source
git:
    depth: false
    
#r_packages:
   - rsconnect
  #- tidyverse
  #- shiny
  #- shinydashboard
  #- viridis
  #- viridislite
  #- sf
  #- stars
  #- units
  #- classint
  #- htmltools
  #- htmlwidgets
  #- leaflet
  #- leaflet.extras
  #- tmaptools 
  #- leafsync
  #- leafem
  #- RColorBrewer
  #- tmap

script:
    - R -f deploy.R
